use_default_settings: true

general:
  instance_name: "RaiaSpace"
  debug: false

server:
  bind_address: "0.0.0.0"
  port: 8080
  secret_key: "5c3cdef553ea35566bf028176d88d2"
  limiter: false
  image_proxy: true

search:
  formats:
    - html
    - json
  safe_search: 1
  autocomplete: "duckduckgo"

ui:
  default_locale: "en"
